import { SpeciesConfig, BrandProducts } from './types';

export const statusConfig: SpeciesConfig = {
  dog: [
    { text: "비만", val: 1.0 },
    { text: "비만 경향", val: 1.4 },
    { text: "중성화 수술", val: 1.6 },
    { text: "운동량 없음", val: 1.8 },
    { text: "가벼운 운동", val: 2.0 },
    { text: "적당한 운동", val: 3.0 },
    { text: "심한 운동", val: 6.0 },
    { text: "성견 체중의 50%이하 (성장기 자견)", val: 3.0 },
    { text: "성견 체중의 50~80% (성장기 자견)", val: 2.5 },
    { text: "성견 체중의 80%이상 (성장기 자견)", val: 2.0 }
  ],
  cat: [
    { text: "비만", val: 1.0 },
    { text: "비만 경향", val: 1.0 },
    { text: "중성화 수술", val: 1.2 },
    { text: "운동량 없음", val: 1.4 },
    { text: "가벼운 운동", val: 1.6 },
    { text: "적당한 운동", val: 2.0 },
    { text: "심한 운동", val: 4.5 },
    { text: "성묘 체중의 50%이하 (성장기 자묘)", val: 3.0 },
    { text: "성묘 체중의 50~80% (성장기 자묘)", val: 2.5 },
    { text: "성묘 체중의 80%이상 (성장기 자묘)", val: 2.0 }
  ]
};

export const brandProductPreset: { dog: BrandProducts; cat: BrandProducts } = {
  dog: {
    natural_balance: [
      { name: "오리지날 울트라 닭 & 보리 레시피 (작은알)", englishName: "Original Ultra Chicken & Barley Recipe (Small Bite)", kcal: 3.590, form: 'dry' },
      { name: "오리지날 울트라 팻독 닭 & 연어 레시피 (큰알)", englishName: "Original Ultra Fat Dogs Chicken Meal, Salmon Meal & Barley Recipe", kcal: 3.070, form: 'dry' },
      { name: "헬스 프로텍션 닭 & 현미 & 호박 레시피 (작은알)", englishName: "Health Protection Chicken, Brown Rice & Pumpkin Recipe Small Breed", kcal: 3.502, form: 'dry' },
      { name: "헬스 프로텍션 닭 & 현미 & 호박 레시피 (큰알)", englishName: "Health Protection Chicken, Brown Rice & Pumpkin Recipe", kcal: 3.502, form: 'dry' },
      { name: "헬스 프로텍션 연어 & 현미 & 호박 레시피 (큰알)", englishName: "Health Protection Salmon, Brown Rice & Pumpkin Recipe", kcal: 3.500, form: 'dry' },
      { name: "헬스 프로텍션 닭 & 현미 & 호박 퍼피 레시피 (작은알)", englishName: "Health Protection Chicken, Brown Rice & Pumpkin Puppy Recipe", kcal: 3.614, form: 'dry' },
      { name: "스페셜라이즈 뉴트리션 센서티브 스킨&스터먹 포뮬라 (큰알)", englishName: "Specialized Nutrition Sensitive Skin & Stomach Salmon & Oatmeal Formula", kcal: 3.605, form: 'dry' },
      { name: "스페셜라이즈 뉴트리션 조인트&머슬 헬스 포뮬라 (큰알)", englishName: "Specialized Nutrition Joint & Muscle Health Chicken & Oatmeal Formula", kcal: 3.590, form: 'dry' },
      { name: "스페셜라이즈 뉴트리션 다이제티브&조인트 헬스 포뮬라 (작은알)", englishName: "Specialized Nutrition Small Breed Digestive & Joint Health Chicken & Oatmeal Formula", kcal: 3.595, form: 'dry' },
      { name: "L.I 그레인프리 연어 & 고구마 레시피 (작은알)", englishName: "Limited Ingredient Grain Free Salmon & Sweet Potato Small Breeds", kcal: 3.360, form: 'dry' },
      { name: "L.I 그레인프리 연어 & 고구마 레시피 (큰알)", englishName: "Limited Ingredient Grain Free Salmon & Sweet Potato Recipe", kcal: 3.450, form: 'dry' },
      { name: "L.I 리저브 그레인프리 오리 & 감자 레시피 (작은알)", englishName: "L.I Reserve Grain Free Duck & Potato Recipe", kcal: 3.571, form: 'dry' },
      { name: "L.I 그레인프리 닭 & 고구마 레시피 (작은알)", englishName: "Limited Ingredient Grain Free Chicken & Sweet Potato Recipe", kcal: 3.510, form: 'dry' },
      { name: "L.I 연어 & 현미 퍼피 레시피 (작은알)", englishName: "Limited Ingredient Salmon & Brown Rice Dry Puppy Recipe", kcal: 3.740, form: 'dry' },
      { name: "L.I 연어 & 현미 레시피 (큰알)", englishName: "Limited Ingredient Salmon & Brown Rice Recipe", kcal: 3.300, form: 'dry' },
      { name: "L.I 닭 & 현미 레시피 (큰알)", englishName: "Limited Ingredient Chicken & Brown Rice Recipe", kcal: 3.445, form: 'dry' },
      { name: "L.I 야채 브로스 코팅 레시피 (작은알)", englishName: "Limited Ingredient Vegetarian Recipe with Veg Broth Coating", kcal: 3.330, form: 'dry' },
      { name: "L.I 야채 레시피 (큰알)", englishName: "L.I. Vegetarian Recipe with Superfood Blend", kcal: 3.480, form: 'dry' }
    ],
    healmedix: [
      { name: "하이포알러제닉 울트라 500+", englishName: "Hypoallergenic Ultra 500+", kcal: 3.687, form: 'dry' },
      { name: "소프트 로우펫", englishName: "Soft Low Fat", kcal: 2.900, form: 'dry' },
      { name: "소프트 모빌리티", englishName: "Soft Mobility", kcal: 3.000, form: 'dry' },
      { name: "소프트 알러제닉", englishName: "Soft Allergenic", kcal: 3.015, form: 'dry' },
      { name: "하이포 다이아베틱", englishName: "Hypo Diabetic", kcal: 3.350, form: 'dry' },
      { name: "유리너리 트랙트", englishName: "Urinary Tract", kcal: 3.880, form: 'dry' },
      { name: "하이포알러제닉 케이천", englishName: "Hypoallergenic Cayenne", kcal: 4.040, form: 'dry' },
      { name: "하이포알러제닉 퓨어프로틴", englishName: "Hypoallergenic Pure Protein", kcal: 4.068, form: 'dry' },
      { name: "하이포알러제닉 웨이트컨트롤", englishName: "Hypoallergenic Weight Control", kcal: 3.600, form: 'dry' },
      { name: "하이포알러제닉 유리너리", englishName: "Hypoallergenic Urinary", kcal: 3.973, form: 'dry' },
      { name: "오비서티", englishName: "Obesity", kcal: 3.200, form: 'dry' },
      { name: "레날", englishName: "Renal", kcal: 3.947, form: 'dry' },
      { name: "헤파틱", englishName: "Hepatic", kcal: 3.980, form: 'dry' },
      { name: "카디악", englishName: "Cardiac", kcal: 3.757, form: 'dry' },
      { name: "모빌리티", englishName: "Mobility", kcal: 3.500, form: 'dry' },
      { name: "인테스티날", englishName: "Intestinal", kcal: 4.020, form: 'dry' },
      { name: "인테스티날 로우펫", englishName: "Intestinal Low Fat", kcal: 3.350, form: 'dry' },
      { name: "아노레딕스 오리", englishName: "Anoredix Duck", kcal: 2.587, form: 'dry' },
      { name: "아노레딕스 닭&칠면조", englishName: "Anoredix Chicken & Turkey", kcal: 2.428, form: 'dry' },
      { name: "프리미엄 닥터힐 스킨케어", englishName: "Premium Dr. Heal Skincare", kcal: 4.050, form: 'dry' },
      { name: "프리미엄 라메르", englishName: "Premium Lamer", kcal: 3.890, form: 'dry' },
      { name: "퓨어프로틴램 습식캔", englishName: "Pure Protein Lamb Wet Can", kcal: 0.837, form: 'wet', packageSizeG: 160, unit: '캔' },
      { name: "리커버리 습식캔", englishName: "Recovery Wet Can", kcal: 1.288, form: 'wet', packageSizeG: 160, unit: '캔' },
      { name: "인테스티날로우펫 습식캔", englishName: "Intestinal Low Fat Wet Can", kcal: 0.952, form: 'wet', packageSizeG: 160, unit: '캔' }
    ],
    royal_canin: [
      { name: "독 유리너리 S/O", englishName: "Canine Urinary SO", kcal: 3.877, form: 'dry' },
      { name: "독 유리너리 S/O 모더레이트 칼로리", englishName: "Canine Urinary SO Moderate Calorie", kcal: 3.323, form: 'dry' },
      { name: "독 유리너리 S/O 스몰독", englishName: "Canine Urinary SO Small Dog", kcal: 3.842, form: 'dry' },
      { name: "독 유리너리S/O+하이포알러제닉", englishName: "Canine Urinary SO + Hypoallergenic", kcal: 3.711, form: 'dry' },
      { name: "유리너리 S/O + 하이포알러제닉 스몰독", englishName: "Urinary SO + Hypoallergenic Small Dog", kcal: 3.714, form: 'dry' },
      { name: "유리너리 S/O + 세타이어티 스몰독", englishName: "Urinary SO + Satiety Small Dog", kcal: 2.564, form: 'dry' },
      { name: "독 가스트로인테스티널", englishName: "Canine Gastrointestinal", kcal: 4.113, form: 'dry' },
      { name: "독 가스트로인테스티널 로우팻", englishName: "Canine Gastrointestinal Low Fat", kcal: 3.46, form: 'dry' },
      { name: "독 가스트로인테스티널 로우팻 스몰독", englishName: "Canine Gastrointestinal Low Fat Small Dog", kcal: 3.458, form: 'dry' },
      { name: "독 가스트로인테스티널 로우팻 + 하이포알러제닉", englishName: "Canine GI Low Fat + Hypoallergenic", kcal: 3.504, form: 'dry' },
      { name: "독 헤파틱", englishName: "Canine Hepatic", kcal: 3.905, form: 'dry' },
      { name: "독 레날", englishName: "Canine Renal", kcal: 3.984, form: 'dry' },
      { name: "독 레날 셀렉트", englishName: "Canine Renal Select", kcal: 3.96, form: 'dry' },
      { name: "독 레날+하이포알러제닉", englishName: "Canine Renal + Hypoallergenic", kcal: 4.019, form: 'dry' },
      { name: "레날 + 하이포알러제닉 스몰독", englishName: "Renal + Hypoallergenic Small Dog", kcal: 4.03, form: 'dry' },
      { name: "독 하이포알러제닉", englishName: "Canine Hypoallergenic (Hydrolyzed Protein HP)", kcal: 4.075, form: 'dry' },
      { name: "독 하이포알러제닉 모더레이트 칼로리", englishName: "Canine Hypoallergenic Moderate Calorie", kcal: 3.767, form: 'dry' },
      { name: "독 하이포알러제닉 + 세타이어티", englishName: "Canine Hypoallergenic + Satiety", kcal: 2.586, form: 'dry' },
      { name: "독 하이포알러제닉 스몰독", englishName: "Canine Hypoallergenic Small Dog", kcal: 3.886, form: 'dry' },
      { name: "독 세타이어티 웨이트 매니지먼트", englishName: "Canine Satiety Weight Management", kcal: 2.586, form: 'dry' },
      { name: "독 세타이어티 웨이트 매니지먼트 스몰독", englishName: "Canine Satiety Weight Management Small Dog", kcal: 2.589, form: 'dry' },
      { name: "독 하이포알러제닉 + 세타이어티 스몰독", englishName: "Canine Hypoallergenic + Satiety Small Dog", kcal: 2.595, form: 'dry' },
      { name: "독 카디악", englishName: "Canine Cardiac", kcal: 4.14, form: 'dry' },
      { name: "[일반식] 독 미니 인도어 어덜트", englishName: "Mini Indoor Adult", kcal: 3.77, form: 'dry' },
      { name: "[일반식] 독 미니 인도어 시니어", englishName: "Mini Indoor Senior", kcal: 3.824, form: 'dry' },
      { name: "[일반식] 독 미니 인도어 퍼피", englishName: "Mini Indoor Puppy", kcal: 3.959, form: 'dry' },
      { name: "[일반식] 독 미니 스타터 마더&베이비독", englishName: "Mini Starter Mother & Babydog", kcal: 4.209, form: 'dry' },
      { name: "독 유리너리 S/O 파우치", englishName: "Canine Urinary SO Pouch", kcal: 0.93, form: 'wet', packageSizeG: 100, unit: '파우치' },
      { name: "독 가스트로인테스티널 로우팻 로프 인 캔 (200g)", englishName: "Canine GI Low Fat Loaf in Sauce Can (200g)", kcal: 0.981, form: 'wet', packageSizeG: 200, unit: '캔' },
      { name: "독 가스트로인테스티널 로우팻 로프 인 캔 (420g)", englishName: "Canine GI Low Fat Loaf in Sauce Can (420g)", kcal: 0.981, form: 'wet', packageSizeG: 420, unit: '캔' },
      { name: "독 가스트로인테스티널 로프 인 캔 (200g)", englishName: "Canine Gastrointestinal Loaf in Sauce Can (200g)", kcal: 1.177, form: 'wet', packageSizeG: 200, unit: '캔' },
      { name: "독 가스트로인테스티널 로프 인 캔 (400g)", englishName: "Canine Gastrointestinal Loaf in Sauce Can (400g)", kcal: 1.177, form: 'wet', packageSizeG: 400, unit: '캔' },
      { name: "독 헤파틱 로프 인 캔", englishName: "Canine Hepatic Loaf in Sauce Can", kcal: 1.465, form: 'wet', packageSizeG: 420, unit: '캔' },
      { name: "독 레날 캔 (200g)", englishName: "Canine Renal Can (200g)", kcal: 1.66, form: 'wet', packageSizeG: 200, unit: '캔' },
      { name: "독 레날 캔 (410g)", englishName: "Canine Renal Can (410g)", kcal: 1.66, form: 'wet', packageSizeG: 410, unit: '캔' },
      { name: "독 카디악 캔", englishName: "Canine Cardiac Can", kcal: 1.311, form: 'wet', packageSizeG: 410, unit: '캔' },
      { name: "리커버리 캔(강아지·고양이 공용)", englishName: "Recovery Can (Dog & Cat)", kcal: 1.24, form: 'wet', packageSizeG: 195, unit: '캔' },
      { name: "독 아이시유 레날 리퀴드", englishName: "Canine ICU Renal Liquid", kcal: 1.30, form: 'wet', packageSizeG: 236, unit: '병' }
    ],
    velixer: [
      { name: "주니어", englishName: "Junior", kcal: 3.575, form: 'dry' },
      { name: "어덜트", englishName: "Adult", kcal: 3.290, form: 'dry' },
      { name: "J/F", englishName: "Joint Formula", kcal: 3.235, form: 'dry' },
      { name: "DM/F", englishName: "Diabetes Mellitus Formula", kcal: 3.140, form: 'dry' },
      { name: "O/F", englishName: "Obesity Formula", kcal: 2.973, form: 'dry' },
      { name: "A/F", englishName: "Atopy Formula", kcal: 3.410, form: 'dry' },
      { name: "LF/F", englishName: "Low Fat Formula", kcal: 2.800, form: 'dry' },
      { name: "I/F", englishName: "Intestinal Formula", kcal: 3.575, form: 'dry' },
      { name: "K/F", englishName: "Kidney Formula", kcal: 3.495, form: 'dry' },
      { name: "L/F", englishName: "Liver Formula", kcal: 3.560, form: 'dry' },
      { name: "H/F", englishName: "Heart Formula", kcal: 3.630, form: 'dry' },
      { name: "UL/F", englishName: "Urinary Formula", kcal: 3.175, form: 'dry' },
      { name: "A3/F", englishName: "Atopy 3 Formula", kcal: 3.300, form: 'dry' },
      { name: "Low Fat/W", englishName: "Low Fat Wet Food", kcal: 0.787, form: 'wet', packageSizeG: 80, unit: '파우치' },
      { name: "I/C", englishName: "Intestinal Cup Food", kcal: 1.109, form: 'wet', packageSizeG: 40, unit: '컵' },
      { name: "D/C", englishName: "Dental Cup Food", kcal: 0.790, form: 'wet', packageSizeG: 40, unit: '컵' },
      { name: "U/C", englishName: "Urinary Cup Food", kcal: 0.790, form: 'wet', packageSizeG: 40, unit: '컵' },
      { name: "R/C", englishName: "Recovery Cup Food", kcal: 1.144, form: 'wet', packageSizeG: 40, unit: '컵' }
    ],
    hills: [
      { name: "퍼피 스몰바이트", englishName: "Puppy Small Bites", kcal: 3.81, form: 'dry' },
      { name: "어덜트 스몰앤미니", englishName: "Adult Small & Mini", kcal: 3.73, form: 'dry' },
      { name: "어덜트 라이트 스몰앤미니", englishName: "Adult Light Small & Mini", kcal: 2.97, form: 'dry' },
      { name: "어덜트 퍼펙트다이제스천", englishName: "Adult Perfect Digestion", kcal: 3.66, form: 'dry' },
      { name: "어덜트 7+ 시니어", englishName: "Adult 7+ Senior", kcal: 3.62, form: 'dry' },
      { name: "i/d", englishName: "Prescription Diet i/d Digestive Care", kcal: 3.589, form: 'dry' },
      { name: "i/d 로우팻", englishName: "Prescription Diet i/d Low Fat Digestive Care", kcal: 3.311, form: 'dry' },
      { name: "z/d", englishName: "Prescription Diet z/d Food Sensitivities", kcal: 3.505, form: 'dry' },
      { name: "z/d 스몰바이트", englishName: "Prescription Diet z/d Small Bites Food Sensitivities", kcal: 3.504, form: 'dry' },
      { name: "z/d 로우팻", englishName: "Prescription Diet z/d Low Fat Hydrolysed Soy Food Sensitivities", kcal: 3.198, form: 'dry' },
      { name: "c/d Multicare", englishName: "Prescription Diet c/d Multicare Urinary Care", kcal: 3.820, form: 'dry' },
      { name: "k/d", englishName: "Prescription Diet k/d Kidney Care", kcal: 3.991, form: 'dry' },
      { name: "w/d 멀티베네핏", englishName: "Prescription Diet w/d Multi-Benefit Glucose Management", kcal: 3.087, form: 'dry' },
      { name: "r/d", englishName: "Prescription Diet r/d Weight Management", kcal: 3.063, form: 'dry' },
      { name: "t/d 스몰바이트", englishName: "Prescription Diet t/d Small Bites Dental Care", kcal: 3.468, form: 'dry' },
      { name: "메타볼릭 스몰바이트", englishName: "Prescription Diet Metabolic Small Bites Weight Management", kcal: 3.121, form: 'dry' },
      { name: "j/d 스몰바이트", englishName: "Prescription Diet j/d Small Bites Joint Care", kcal: 3.670, form: 'dry' },
      { name: "h/d", englishName: "Prescription Diet h/d Heart Care", kcal: 4.002, form: 'dry' },
      { name: "u/d", englishName: "Prescription Diet u/d Urinary Care", kcal: 3.986, form: 'dry' },
      { name: "l/d", englishName: "Prescription Diet l/d Liver Care", kcal: 3.995, form: 'dry' },
      { name: "ONC 케어", englishName: "Prescription Diet ONC Care Restorative Care", kcal: 4.158, form: 'dry' },
      { name: "GI 바이옴 스몰바이트", englishName: "Prescription Diet Gastrointestinal Biome Small Bites Digestive Care", kcal: 3.327, form: 'dry' },
      { name: "z/d 로우팻 캔", englishName: "Prescription Diet z/d Low Fat Hydrolysed Soy Food Sensitivities Canned", kcal: 0.924, form: 'wet', packageSizeG: 370, unit: '캔' },
      { name: "k/d 캔 (156g)", englishName: "Prescription Diet k/d Chicken & Vegetable Stew Kidney Care Canned (156g)", kcal: 0.995, form: 'wet', packageSizeG: 156, unit: '캔' },
      { name: "k/d 캔 (354g)", englishName: "Prescription Diet k/d Chicken & Vegetable Stew Kidney Care Canned (354g)", kcal: 0.994, form: 'wet', packageSizeG: 354, unit: '캔' },
      { name: "l/d 캔", englishName: "Prescription Diet l/d Liver Care Canned", kcal: 1.527, form: 'wet', packageSizeG: 370, unit: '캔' },
      { name: "c/d Multicare 캔 (156g)", englishName: "Prescription Diet c/d Multicare Chicken & Vegetable Stew Urinary Care Canned (156g)", kcal: 0.751, form: 'wet', packageSizeG: 156, unit: '캔' },
      { name: "c/d Multicare 캔 (354g)", englishName: "Prescription Diet c/d Multicare Chicken & Vegetable Stew Urinary Care Canned (354g)", kcal: 0.751, form: 'wet', packageSizeG: 354, unit: '캔' },
      { name: "w/d 멀티베네핏 캔", englishName: "Prescription Diet w/d Multi-Benefit Vegetable & Chicken Stew Glucose Management Canned", kcal: 0.568, form: 'wet', packageSizeG: 354, unit: '캔' }
    ]
  },
  cat: {
    natural_balance: [
      { name: "오리지날 울트라 닭 & 연어 레시피", englishName: "Original Ultra Chicken & Salmon Recipe", kcal: 3.920, form: 'dry' },
      { name: "오리지날 울트라 그레인프리 인도어 닭 & 연어 레시피", englishName: "Original Ultra Indoor G/F Chicken & Salmon Recipe", kcal: 3.800, form: 'dry' },
      { name: "오리지날 울트라 팻캣 닭 & 연어 레시피", englishName: "Original Ultra Fat Cats Chicken & Salmon Recipe", kcal: 3.200, form: 'dry' },
      { name: "L.I 그레인프리 연어 & 완두 레시피", englishName: "Limited Ingredient Grain Free Salmon & Green Pea Recipe", kcal: 3.500, form: 'dry' },
      { name: "울트라 프로틴 리얼 치킨 키튼 캣 레시피", englishName: "Ultra Protein Real Chicken & Chicken Meal Kitten Cat Recipe", kcal: 3.530, form: 'dry' },
      { name: "울트라 프로틴 리얼 치킨 캣 레시피", englishName: "Ultra Protein Real Chicken & Chicken Meal Cat Recipe", kcal: 3.530, form: 'dry' },
      { name: "울트라 프로틴 리얼 살몬 & 치킨 캣 레시피", englishName: "Ultra Protein Real Salmon & Chicken Meal Cat Recipe", kcal: 3.590, form: 'dry' },
      { name: "울트라 프로틴+ 이뮨 & 다이제스티브 캣 레시피", englishName: "Ultra Protein Plus Immune & Digestive Health Cat Recipe", kcal: 3.570, form: 'dry' },
      { name: "울트라 프로틴+ 스킨 & 코트 & 다이제스티브 캣 레시피", englishName: "Ultra Protein Plus Skin & Coat & Digestive Health Cat Recipe", kcal: 3.570, form: 'dry' },
      { name: "오리지날 울트라 닭&닭간 레시피 파테 캔", englishName: "Original Ultra Chicken & Liver Recipe Pate Canned", kcal: 1.26, form: 'wet', packageSizeG: 85, unit: '캔' },
      { name: "오리지날 울트라 오션피쉬 레시피 파테 캔", englishName: "Original Ultra Ocean Fish Recipe Pate Canned", kcal: 1.26, form: 'wet', packageSizeG: 85, unit: '캔' },
      { name: "오리지날 울트라 인도어 닭 레시피 파테 캔", englishName: "Original Ultra Indoor Chicken Recipe Pate Canned", kcal: 1.27, form: 'wet', packageSizeG: 156, unit: '캔' },
      { name: "오리지날 울트라 연어 레시피 파테 캔", englishName: "Original Ultra Salmon Recipe Pate Canned", kcal: 1.04, form: 'wet', packageSizeG: 156, unit: '캔' },
      { name: "오리지날 울트라 참치&새우 레시피 파테 캔", englishName: "Original Ultra Tuna & Shrimp Recipe Pate Canned", kcal: 1.07, form: 'wet', packageSizeG: 156, unit: '캔' },
      { name: "울트라 프로틴+ 스킨&코트&다이제스티브 레시피 퓨레", englishName: "Ultra Protein Plus Skin & Coat & Digestive Recipe Puree Cat", kcal: 1.099, form: 'wet', packageSizeG: 68, unit: '파우치' },
      { name: "울트라 프로틴+ 이뮨&다이제스티브 레시피 퓨레", englishName: "Ultra Protein Plus Immune & Digestive Recipe Puree Cat", kcal: 1.110, form: 'wet', packageSizeG: 68, unit: '파우치' }
    ],
    healmedix: [
      { name: "유리너리 트랙트 필라인", englishName: "Urinary Tract Feline", kcal: 3.870, form: 'dry' },
      { name: "웨이트컨트롤 필라인", englishName: "Weight Control Feline", kcal: 3.160, form: 'dry' },
      { name: "인테스티날 필라인", englishName: "Intestinal Feline", kcal: 4.191, form: 'dry' }
    ],
    royal_canin: [
      { name: "캣 유리너리 S/O", englishName: "Feline Urinary SO", kcal: 3.861, form: 'dry' },
      { name: "캣 유리너리S/O+하이포알러제닉", englishName: "Feline Urinary SO + Hypoallergenic", kcal: 3.77, form: 'dry' },
      { name: "캣 하이포알러제닉", englishName: "Feline Hypoallergenic (Hydrolyzed Protein HP)", kcal: 4.087, form: 'dry' },
      { name: "캣 가스트로인테스티널", englishName: "Feline Gastrointestinal", kcal: 4.091, form: 'dry' },
      { name: "캣 가스트로인테스티널 화이버 리스폰스", englishName: "Feline Gastrointestinal Fibre Response", kcal: 3.90, form: 'dry' },
      { name: "캣 다이아베틱", englishName: "Feline Diabetic (Glycobalance)", kcal: 3.856, form: 'dry' },
      { name: "캣 사티에티 서포트", englishName: "Feline Satiety Weight Management", kcal: 3.074, form: 'dry' },
      { name: "캣 레날 스페셜", englishName: "Feline Renal Special", kcal: 3.919, form: 'dry' },
      { name: "캣 카디악", englishName: "Feline Cardiac", kcal: 3.75, form: 'dry' },
      { name: "캣 유리너리 S/O + 블래더 컴포트", englishName: "Feline Multifunction Urinary SO + Bladder Comfort", kcal: 3.563, form: 'dry' },
      { name: "캣 유리너리 S/O 머셀 인 그레이비 파우치", englishName: "Feline Urinary SO Morsels in Gravy Pouch", kcal: 0.832, form: 'wet', packageSizeG: 85, unit: '파우치' },
      { name: "캣 가스트로인테스티널 화이버 리스폰스 그레이비 파우치", englishName: "Feline GI Fibre Response Gravy Pouch", kcal: 0.71, form: 'wet', packageSizeG: 85, unit: '파우치' },
      { name: "캣 가스트로인테스티널 씬 슬라이스 인 그레이비 파우치", englishName: "Feline Gastrointestinal Thin Slices Pouch", kcal: 1.029, form: 'wet', packageSizeG: 85, unit: '파우치' },
      { name: "캣 레날 파우치", englishName: "Feline Renal Pouch", kcal: 1.093, form: 'wet', packageSizeG: 85, unit: '파우치' },
      { name: "리커버리 캔(강아지·고양이 공용)", englishName: "Recovery Can (Dog & Cat)", kcal: 1.24, form: 'wet', packageSizeG: 195, unit: '캔' },
      { name: "[일반식] 캣 마더 앤 베이비캣", englishName: "Mother & Babycat", kcal: 4.422, form: 'dry' },
      { name: "[일반식] 캣 키튼", englishName: "Kitten", kcal: 4.068, form: 'dry' }
    ],
    velixer: [
      { name: "O/F", englishName: "Obesity Formula Cat", kcal: 3.090, form: 'dry' },
      { name: "F1/F", englishName: "Hypoallergenic Formula Cat", kcal: 3.140, form: 'dry' }
    ],
    hills: [
      { name: "키튼 치킨", englishName: "Kitten Chicken", kcal: 4.25, form: 'dry' },
      { name: "어덜트 실내묘 치킨", englishName: "Adult Indoor Chicken", kcal: 3.55, form: 'dry' },
      { name: "어덜트 헤어볼 컨트롤", englishName: "Adult Hairball Control", kcal: 3.69, form: 'dry' },
      { name: "어덜트 라이트", englishName: "Adult Light", kcal: 3.17, form: 'dry' },
      { name: "i/d", englishName: "Prescription Diet i/d Digestive Care", kcal: 3.934, form: 'dry' },
      { name: "c/d Multicare", englishName: "Prescription Diet c/d Multicare Urinary Care", kcal: 3.896, form: 'dry' },
      { name: "c/d Multicare 스트레스", englishName: "Prescription Diet c/d Multicare Stress Urinary Care", kcal: 3.844, form: 'dry' },
      { name: "c/d Multicare+메타볼릭", englishName: "Prescription Diet c/d Multicare+Metabolic Urinary Care", kcal: 3.255, form: 'dry' },
      { name: "k/d", englishName: "Prescription Diet k/d Kidney Care (Chicken)", kcal: 4.083, form: 'dry' },
      { name: "k/d (오션피쉬)", englishName: "Prescription Diet k/d Kidney Care (Ocean Fish/Tuna)", kcal: 4.084, form: 'dry' },
      { name: "k/d 얼리 서포트", englishName: "Prescription Diet k/d Early Stage Support Kidney Care", kcal: 4.082, form: 'dry' },
      { name: "z/d", englishName: "Prescription Diet z/d Food Sensitivities", kcal: 3.847, form: 'dry' },
      { name: "m/d", englishName: "Prescription Diet m/d", kcal: 3.95, form: 'dry' },
      { name: "Metabolic", englishName: "Prescription Diet Metabolic Weight Management", kcal: 3.398, form: 'dry' },
      { name: "y/d", englishName: "Prescription Diet y/d Thyroid Care", kcal: 4.005, form: 'dry' },
      { name: "GI 바이옴", englishName: "Prescription Diet Gastrointestinal Biome Stress Digestive Care", kcal: 3.807, form: 'dry' },
      { name: "Multi-Organ", englishName: "Prescription Diet Multi-Organ Care", kcal: 3.840, form: 'dry' },
      { name: "ONC 케어", englishName: "Prescription Diet ONC Care Restorative Care", kcal: 4.187, form: 'dry' },
      { name: "t/d", englishName: "Prescription Diet t/d Dental Care", kcal: 3.577, form: 'dry' },
      { name: "w/d 멀티베네핏", englishName: "Prescription Diet w/d Multi-Benefit Glucose Management", kcal: 3.228, form: 'dry' },
      { name: "i/d 치킨 파테 캔", englishName: "Prescription Diet i/d Chicken Pate Digestive Care Canned", kcal: 1.103, form: 'wet', packageSizeG: 156, unit: '캔' },
      { name: "i/d 치킨&베지터블 스튜 캔", englishName: "Prescription Diet i/d Chicken & Vegetable Stew Digestive Care Canned", kcal: 0.890, form: 'wet', packageSizeG: 82, unit: '캔' },
      { name: "i/d 키튼 캔", englishName: "Prescription Diet i/d Kitten Chicken Pate Digestive Care Canned", kcal: 1.109, form: 'wet', packageSizeG: 156, unit: '캔' },
      { name: "c/d Multicare 스트레스 캔", englishName: "Prescription Diet c/d Multicare Stress Vegetable & Tuna Stew Urinary Care Canned", kcal: 0.810, form: 'wet', packageSizeG: 82, unit: '캔' },
      { name: "Multi-Organ 캔", englishName: "Prescription Diet Multi-Organ Chicken Minced Multi-Organ Care Canned", kcal: 1.098, form: 'wet', packageSizeG: 156, unit: '캔' },
      { name: "w/d 멀티베네핏 캔", englishName: "Prescription Diet w/d Chicken Glucose Management Canned", kcal: 0.821, form: 'wet', packageSizeG: 156, unit: '캔' },
      { name: "z/d 캔", englishName: "Prescription Diet z/d Food Sensitivities Canned", kcal: 1.109, form: 'wet', packageSizeG: 156, unit: '캔' }
    ]
  }
};
